local M = {}

function M.apply(p)
  local hi = function(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
  end

  -- Editor
  hi('Normal', { fg = p.text, bg = p.bg })
  hi('NormalFloat', { fg = p.text, bg = p.dark1 })
  hi('FloatBorder', { fg = p.dimmed4, bg = p.dark1 })
  hi('FloatTitle', { fg = p.accent3, bg = p.dark1, bold = true })
  hi('Cursor', { fg = p.bg, bg = p.text })
  hi('CursorLine', { bg = p.dimmed5 })
  hi('CursorLineNr', { fg = p.text, bold = true })
  hi('LineNr', { fg = p.dimmed4 })
  hi('SignColumn', { bg = p.bg })
  hi('ColorColumn', { bg = p.dimmed5 })
  hi('Visual', { bg = p.dimmed4 })
  hi('VisualNOS', { bg = p.dimmed4 })
  hi('Search', { fg = p.dark2, bg = p.accent3 })
  hi('IncSearch', { fg = p.dark2, bg = p.accent2 })
  hi('CurSearch', { fg = p.dark2, bg = p.accent2 })
  hi('Substitute', { fg = p.dark2, bg = p.accent1 })
  hi('MatchParen', { fg = p.accent3, bold = true, underline = true })
  hi('Pmenu', { fg = p.text, bg = p.dark1 })
  hi('PmenuSel', { fg = p.text, bg = p.dimmed4 })
  hi('PmenuSbar', { bg = p.dimmed5 })
  hi('PmenuThumb', { bg = p.dimmed3 })
  hi('StatusLine', { fg = p.text, bg = p.dark1 })
  hi('StatusLineNC', { fg = p.dimmed3, bg = p.dark1 })
  hi('TabLine', { fg = p.dimmed2, bg = p.dark1 })
  hi('TabLineSel', { fg = p.text, bg = p.bg })
  hi('TabLineFill', { bg = p.dark2 })
  hi('WinSeparator', { fg = p.dimmed5 })
  hi('Folded', { fg = p.dimmed2, bg = p.dimmed5 })
  hi('FoldColumn', { fg = p.dimmed4 })
  hi('NonText', { fg = p.dimmed4 })
  hi('SpecialKey', { fg = p.dimmed4 })
  hi('Whitespace', { fg = p.dimmed5 })
  hi('EndOfBuffer', { fg = p.bg })
  hi('Directory', { fg = p.accent5 })
  hi('Title', { fg = p.accent3, bold = true })
  hi('ErrorMsg', { fg = p.accent1 })
  hi('WarningMsg', { fg = p.accent2 })
  hi('ModeMsg', { fg = p.text })
  hi('MoreMsg', { fg = p.accent4 })
  hi('Question', { fg = p.accent5 })
  hi('WildMenu', { fg = p.dark2, bg = p.accent3 })
  hi('Conceal', { fg = p.dimmed3 })
  hi('WinBar', { fg = p.dimmed1, bg = p.bg })
  hi('WinBarNC', { fg = p.dimmed3, bg = p.bg })
  hi('SpellBad', { undercurl = true, sp = p.accent1 })
  hi('SpellCap', { undercurl = true, sp = p.accent3 })
  hi('SpellLocal', { undercurl = true, sp = p.accent5 })
  hi('SpellRare', { undercurl = true, sp = p.accent6 })
  hi('QuickFixLine', { bg = p.dimmed5 })
  hi('DiffAdd', { bg = '#2a3520' })
  hi('DiffChange', { bg = '#2a2a20' })
  hi('DiffDelete', { fg = p.accent1, bg = '#3a2020' })
  hi('DiffText', { bg = '#3a3520' })

  -- Syntax
  hi('Comment', { fg = p.dimmed3, italic = true })
  hi('Constant', { fg = p.accent6 })
  hi('String', { fg = p.accent3 })
  hi('Character', { fg = p.accent6 })
  hi('Number', { fg = p.accent6 })
  hi('Boolean', { fg = p.accent6 })
  hi('Float', { fg = p.accent6 })
  hi('Identifier', { fg = p.text })
  hi('Function', { fg = p.accent4 })
  hi('Statement', { fg = p.accent1 })
  hi('Conditional', { fg = p.accent1 })
  hi('Repeat', { fg = p.accent1 })
  hi('Label', { fg = p.accent1 })
  hi('Operator', { fg = p.accent1 })
  hi('Keyword', { fg = p.accent1 })
  hi('Exception', { fg = p.accent1 })
  hi('PreProc', { fg = p.accent1 })
  hi('Include', { fg = p.accent1 })
  hi('Define', { fg = p.accent1 })
  hi('Macro', { fg = p.accent5 })
  hi('PreCondit', { fg = p.accent1 })
  hi('Type', { fg = p.accent5, italic = true })
  hi('StorageClass', { fg = p.accent1, italic = true })
  hi('Structure', { fg = p.accent5 })
  hi('Typedef', { fg = p.accent5, italic = true })
  hi('Special', { fg = p.accent2 })
  hi('SpecialChar', { fg = p.accent6 })
  hi('Tag', { fg = p.accent1 })
  hi('Delimiter', { fg = p.dimmed1 })
  hi('SpecialComment', { fg = p.dimmed2 })
  hi('Debug', { fg = p.accent2 })
  hi('Underlined', { underline = true })
  hi('Error', { fg = p.accent1 })
  hi('Todo', { fg = p.accent3, bold = true })

  -- Treesitter
  hi('@variable', { fg = p.text })
  hi('@variable.builtin', { fg = p.accent6, italic = true })
  hi('@variable.parameter', { fg = p.accent2, italic = true })
  hi('@variable.member', { fg = p.text })
  hi('@constant', { fg = p.accent6 })
  hi('@constant.builtin', { fg = p.accent6 })
  hi('@constant.macro', { fg = p.accent6 })
  hi('@module', { fg = p.accent5, italic = true })
  hi('@label', { fg = p.accent1 })
  hi('@string', { fg = p.accent3 })
  hi('@string.escape', { fg = p.accent6 })
  hi('@string.regexp', { fg = p.accent1 })
  hi('@string.special', { fg = p.accent6 })
  hi('@character', { fg = p.accent6 })
  hi('@number', { fg = p.accent6 })
  hi('@boolean', { fg = p.accent6 })
  hi('@float', { fg = p.accent6 })
  hi('@function', { fg = p.accent4 })
  hi('@function.builtin', { fg = p.accent4 })
  hi('@function.call', { fg = p.accent4 })
  hi('@function.macro', { fg = p.accent5 })
  hi('@function.method', { fg = p.accent4 })
  hi('@function.method.call', { fg = p.accent4 })
  hi('@constructor', { fg = p.accent5 })
  hi('@operator', { fg = p.accent1 })
  hi('@keyword', { fg = p.accent1 })
  hi('@keyword.coroutine', { fg = p.accent1 })
  hi('@keyword.function', { fg = p.accent5, italic = true })
  hi('@keyword.operator', { fg = p.accent1 })
  hi('@keyword.import', { fg = p.accent1 })
  hi('@keyword.type', { fg = p.accent5, italic = true })
  hi('@keyword.modifier', { fg = p.accent1, italic = true })
  hi('@keyword.repeat', { fg = p.accent1 })
  hi('@keyword.return', { fg = p.accent1 })
  hi('@keyword.exception', { fg = p.accent1 })
  hi('@keyword.conditional', { fg = p.accent1 })
  hi('@punctuation.delimiter', { fg = p.dimmed1 })
  hi('@punctuation.bracket', { fg = p.dimmed1 })
  hi('@punctuation.special', { fg = p.accent1 })
  hi('@comment', { fg = p.dimmed3, italic = true })
  hi('@comment.documentation', { fg = p.dimmed2, italic = true })
  hi('@comment.todo', { fg = p.accent3, bold = true })
  hi('@comment.note', { fg = p.accent5, bold = true })
  hi('@comment.warning', { fg = p.accent2, bold = true })
  hi('@comment.error', { fg = p.accent1, bold = true })
  hi('@type', { fg = p.accent5, italic = true })
  hi('@type.builtin', { fg = p.accent5, italic = true })
  hi('@type.qualifier', { fg = p.accent1, italic = true })
  hi('@attribute', { fg = p.accent4 })
  hi('@property', { fg = p.text })
  hi('@tag', { fg = p.accent1 })
  hi('@tag.attribute', { fg = p.accent4, italic = true })
  hi('@tag.delimiter', { fg = p.dimmed1 })
  hi('@markup.heading', { fg = p.accent3, bold = true })
  hi('@markup.italic', { italic = true })
  hi('@markup.strong', { bold = true })
  hi('@markup.strikethrough', { strikethrough = true })
  hi('@markup.underline', { underline = true })
  hi('@markup.raw', { fg = p.accent4 })
  hi('@markup.link', { fg = p.accent5 })
  hi('@markup.link.url', { fg = p.accent5, underline = true })
  hi('@markup.list', { fg = p.accent1 })

  -- LSP Semantic Tokens
  hi('@lsp.type.namespace', { fg = p.accent5, italic = true })
  hi('@lsp.type.type', { fg = p.accent5, italic = true })
  hi('@lsp.type.class', { fg = p.accent5 })
  hi('@lsp.type.enum', { fg = p.accent5 })
  hi('@lsp.type.interface', { fg = p.accent5, italic = true })
  hi('@lsp.type.struct', { fg = p.accent5 })
  hi('@lsp.type.parameter', { fg = p.accent2, italic = true })
  hi('@lsp.type.variable', { fg = p.text })
  hi('@lsp.type.property', { fg = p.text })
  hi('@lsp.type.enumMember', { fg = p.accent6 })
  hi('@lsp.type.function', { fg = p.accent4 })
  hi('@lsp.type.method', { fg = p.accent4 })
  hi('@lsp.type.macro', { fg = p.accent5 })
  hi('@lsp.type.decorator', { fg = p.accent4, italic = true })

  -- Diagnostics
  hi('DiagnosticError', { fg = p.accent1 })
  hi('DiagnosticWarn', { fg = p.accent2 })
  hi('DiagnosticInfo', { fg = p.accent5 })
  hi('DiagnosticHint', { fg = p.accent6 })
  hi('DiagnosticOk', { fg = p.accent4 })
  hi('DiagnosticUnderlineError', { undercurl = true, sp = p.accent1 })
  hi('DiagnosticUnderlineWarn', { undercurl = true, sp = p.accent2 })
  hi('DiagnosticUnderlineInfo', { undercurl = true, sp = p.accent5 })
  hi('DiagnosticUnderlineHint', { undercurl = true, sp = p.accent6 })
  hi('DiagnosticUnderlineOk', { undercurl = true, sp = p.accent4 })
  hi('DiagnosticVirtualTextError', { fg = p.accent1, bg = '#3a2020' })
  hi('DiagnosticVirtualTextWarn', { fg = p.accent2, bg = '#3a2a20' })
  hi('DiagnosticVirtualTextInfo', { fg = p.accent5, bg = '#203a3a' })
  hi('DiagnosticVirtualTextHint', { fg = p.accent6, bg = '#2a2a3a' })

  -- GitSigns
  hi('GitSignsAdd', { fg = p.accent4 })
  hi('GitSignsChange', { fg = p.accent3 })
  hi('GitSignsDelete', { fg = p.accent1 })
  hi('GitSignsCurrentLineBlame', { fg = p.dimmed3, italic = true })

  -- Telescope
  hi('TelescopeNormal', { fg = p.text, bg = p.dark1 })
  hi('TelescopeBorder', { fg = p.dimmed4, bg = p.dark1 })
  hi('TelescopeTitle', { fg = p.accent3, bold = true })
  hi('TelescopePromptNormal', { fg = p.text, bg = p.dimmed5 })
  hi('TelescopePromptBorder', { fg = p.dimmed5, bg = p.dimmed5 })
  hi('TelescopePromptTitle', { fg = p.dark2, bg = p.accent1, bold = true })
  hi('TelescopePromptPrefix', { fg = p.accent1 })
  hi('TelescopePromptCounter', { fg = p.dimmed2 })
  hi('TelescopeResultsNormal', { fg = p.dimmed1, bg = p.dark1 })
  hi('TelescopeResultsBorder', { fg = p.dark1, bg = p.dark1 })
  hi('TelescopeResultsTitle', { fg = p.dark1, bg = p.dark1 })
  hi('TelescopePreviewNormal', { bg = p.dark2 })
  hi('TelescopePreviewBorder', { fg = p.dark2, bg = p.dark2 })
  hi('TelescopePreviewTitle', { fg = p.dark2, bg = p.accent4, bold = true })
  hi('TelescopeSelection', { fg = p.text, bg = p.dimmed5 })
  hi('TelescopeSelectionCaret', { fg = p.accent1, bg = p.dimmed5 })
  hi('TelescopeMatching', { fg = p.accent1, bold = true })

  -- Which-Key
  hi('WhichKey', { fg = p.accent1 })
  hi('WhichKeyGroup', { fg = p.accent5 })
  hi('WhichKeyDesc', { fg = p.text })
  hi('WhichKeySeparator', { fg = p.dimmed3 })
  hi('WhichKeyFloat', { bg = p.dark1 })
  hi('WhichKeyBorder', { fg = p.dimmed4, bg = p.dark1 })
  hi('WhichKeyValue', { fg = p.dimmed2 })

  -- Neo-tree
  hi('NeoTreeNormal', { fg = p.dimmed1, bg = p.dark1 })
  hi('NeoTreeNormalNC', { fg = p.dimmed1, bg = p.dark1 })
  hi('NeoTreeDirectoryName', { fg = p.accent5 })
  hi('NeoTreeDirectoryIcon', { fg = p.accent5 })
  hi('NeoTreeRootName', { fg = p.accent3, bold = true })
  hi('NeoTreeFileName', { fg = p.dimmed1 })
  hi('NeoTreeFileIcon', { fg = p.dimmed2 })
  hi('NeoTreeGitAdded', { fg = p.accent4 })
  hi('NeoTreeGitModified', { fg = p.accent3 })
  hi('NeoTreeGitDeleted', { fg = p.accent1 })
  hi('NeoTreeGitConflict', { fg = p.accent2, bold = true })
  hi('NeoTreeGitUntracked', { fg = p.dimmed2, italic = true })
  hi('NeoTreeIndentMarker', { fg = p.dimmed5 })
  hi('NeoTreeCursorLine', { bg = p.dimmed5 })
  hi('NeoTreeWinSeparator', { fg = p.dark1, bg = p.dark1 })

  -- Indent Blankline
  hi('IblIndent', { fg = p.dimmed5 })
  hi('IblScope', { fg = p.dimmed4 })

  -- Blink.cmp
  hi('BlinkCmpMenu', { fg = p.text, bg = p.dark1 })
  hi('BlinkCmpMenuBorder', { fg = p.dimmed4, bg = p.dark1 })
  hi('BlinkCmpMenuSelection', { bg = p.dimmed5 })
  hi('BlinkCmpLabel', { fg = p.text })
  hi('BlinkCmpLabelMatch', { fg = p.accent1, bold = true })
  hi('BlinkCmpLabelDeprecated', { fg = p.dimmed3, strikethrough = true })
  hi('BlinkCmpKind', { fg = p.accent5 })
  hi('BlinkCmpDoc', { fg = p.text, bg = p.dark2 })
  hi('BlinkCmpDocBorder', { fg = p.dimmed4, bg = p.dark2 })
  hi('BlinkCmpSignatureHelp', { fg = p.text, bg = p.dark1 })
  hi('BlinkCmpSignatureHelpBorder', { fg = p.dimmed4, bg = p.dark1 })
  hi('BlinkCmpKindFunction', { fg = p.accent4 })
  hi('BlinkCmpKindMethod', { fg = p.accent4 })
  hi('BlinkCmpKindVariable', { fg = p.accent1 })
  hi('BlinkCmpKindField', { fg = p.accent1 })
  hi('BlinkCmpKindKeyword', { fg = p.accent6 })
  hi('BlinkCmpKindSnippet', { fg = p.accent2 })
  hi('BlinkCmpKindText', { fg = p.dimmed1 })
  hi('BlinkCmpKindClass', { fg = p.accent5 })
  hi('BlinkCmpKindStruct', { fg = p.accent5 })
  hi('BlinkCmpKindInterface', { fg = p.accent5 })
  hi('BlinkCmpKindModule', { fg = p.accent5 })
  hi('BlinkCmpKindProperty', { fg = p.accent1 })
  hi('BlinkCmpKindEnum', { fg = p.accent5 })
  hi('BlinkCmpKindEnumMember', { fg = p.accent6 })
  hi('BlinkCmpKindConstant', { fg = p.accent6 })
  hi('BlinkCmpKindValue', { fg = p.accent6 })
end

return M
